### ISSUE TITLE
Дописать META-INF в chengine.spring-boot-starter для конфигрурирования через yaml

### ISSUE THREAD

**Issue by mikheevshow** [mikheevshow/chengine#7]

**Comment by mikheevshow** [comment]
Добавить в json схему возможность указания списка подключаемых ботов

``` yaml

bots:
 - bot:
    qalifier:
    username:
    token:
    webhook: 
 - bot:
    qalifier:
    username:
    token:
    webhook: 
 ..................

```
